//Products
export const GET_PRODUCT_BY_ID_REQUEST = 'GET_PRODUCT_BY_ID_REQUEST'
export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'
export const GET_PRODUCT_BY_ID_ERROR = 'GET_PRODUCT_BY_ID_ERROR'

export const GET_PRODUCT_BY_PART_NUMBER_REQUEST = 'GET_PRODUCT_BY_PART_NUMBER_REQUEST'
export const GET_PRODUCT_BY_PART_NUMBER_SUCCESS = 'GET_PRODUCT_BY_PART_NUMBER_SUCCESS'
export const GET_PRODUCT_BY_PART_NUMBER_ERROR = 'GET_PRODUCT_BY_PART_NUMBER_ERROR'

export const GET_PRODUCTS_BY_PART_NUMBERS_REQUEST = 'GET_PRODUCTS_BY_PART_NUMBERS_REQUEST'
export const GET_PRODUCTS_BY_PART_NUMBERS_SUCCESS = 'GET_PRODUCTS_BY_PART_NUMBERS_SUCCESS'
export const GET_PRODUCTS_BY_PART_NUMBERS_ERROR = 'GET_PRODUCTS_BY_PART_NUMBERS_ERROR'

//Other
export const NETWORK_OPERATION_START = 'NETWORK_OPERATION_START'
export const NETWORK_OPERATION_END = 'NETWORK_OPERATION_END'